export const EMPTY_TASKS_DATA = {
    ALL: [],
    IN_PROGRESS: [],
    ASSIGNED: [],
    AVAILABLE: [],
    UNASSIGNED: [],
    BLOCKED: [],
    NEEDS_REVIEW: [],
    IN_REVIEW: [],
    VERIFIED: [],
    MERGED: [],
    COMPLETED: [],
    OVERDUE: [],
    DONE: [],
};
