export const mockGetTaskProgress = {
    message: 'Progress document retrieved successfully.',
    count: 3,
    data: [
        {
            id: '2jFmAjKstXYDqgZ5KWQ3',
            date: 1685232000000,
            createdAt: 1685311737895,
            blockers: '1',
            completed: '1',
            planned: '1',
            type: 'task',
            userData: {
                id: 'xpHuUkihhxPeWYfNe38L',
                incompleteUserDetails: false,
                roles: {
                    archived: false,
                    super_user: false,
                    admin: false,
                    member: true,
                },
                linkedin_id: 'muralidhar-akkireddy-91b673158',
                last_name: 'Akkireddy',
                yoe: 1,
                github_display_name: 'Muralidhar',
                github_id: 'Muralidhar22',
                company: 'Tata Consultancy Services',
                designation: 'Assistant Systems Engineer',
                twitter_id: 'murali_14',
                first_name: 'Muralidhar',
                username: 'muralidhar',
                status: 'idle',
                picture: {
                    url: 'https://res.cloudinary.com/realdevsquad/image/upload/v1661061375/profile/xpHuUkihhxPeWYfNe38L/ogirikotjnz8esjpm51v.jpg',
                    publicId:
                        'profile/xpHuUkihhxPeWYfNe38L/ogirikotjnz8esjpm51v',
                },
            },
            taskId: 'OxYqJgf6Tyl90uci1mzs',
        },
        {
            id: 'cYUvDNwE7KHIx12L5Krh',
            date: 1685145600000,
            createdAt: 1685165867518,
            blockers: 'test',
            completed: 'testig task progress',
            planned: 'plan to test',
            type: 'task',
            userData: {
                id: 'xpHuUkihhxPeWYfNe38L',
                incompleteUserDetails: false,
                roles: {
                    archived: false,
                    super_user: false,
                    admin: false,
                    member: true,
                },
                linkedin_id: 'muralidhar-akkireddy-91b673158',
                last_name: 'Akkireddy',
                yoe: 1,
                github_display_name: 'Muralidhar',
                github_id: 'Muralidhar22',
                company: 'Tata Consultancy Services',
                designation: 'Assistant Systems Engineer',
                twitter_id: 'murali_14',
                first_name: 'Muralidhar',
                username: 'muralidhar',
                status: 'idle',
                picture: {
                    url: 'https://res.cloudinary.com/realdevsquad/image/upload/v1661061375/profile/xpHuUkihhxPeWYfNe38L/ogirikotjnz8esjpm51v.jpg',
                    publicId:
                        'profile/xpHuUkihhxPeWYfNe38L/ogirikotjnz8esjpm51v',
                },
            },
            taskId: 'OxYqJgf6Tyl90uci1mzs',
        },
        {
            id: 'zJHdjzAsvH8K6wg7vgM6',
            date: 1685491200000,
            createdAt: 1685515802271,
            blockers: 'none',
            completed: 'progress 2',
            planned: 'something planned',
            type: 'task',
            userData: {
                id: 'xpHuUkihhxPeWYfNe38L',
                incompleteUserDetails: false,
                roles: {
                    archived: false,
                    super_user: false,
                    admin: false,
                    member: true,
                },
                linkedin_id: 'muralidhar-akkireddy-91b673158',
                last_name: 'Akkireddy',
                yoe: 1,
                github_display_name: 'Muralidhar',
                github_id: 'Muralidhar22',
                company: 'Tata Consultancy Services',
                designation: 'Assistant Systems Engineer',
                twitter_id: 'murali_14',
                first_name: 'Muralidhar',
                username: 'muralidhar',
                status: 'idle',
                picture: {
                    url: 'https://res.cloudinary.com/realdevsquad/image/upload/v1661061375/profile/xpHuUkihhxPeWYfNe38L/ogirikotjnz8esjpm51v.jpg',
                    publicId:
                        'profile/xpHuUkihhxPeWYfNe38L/ogirikotjnz8esjpm51v',
                },
            },
            taskId: 'OxYqJgf6Tyl90uci1mzs',
        },
        {
            id: 'zJHdjzAsvH8K6wg7de07',
            date: 1685491203632,
            createdAt: 1685515806473,
            blockers:
                'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
            completed:
                'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
            planned:
                'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
            type: 'task',
            userData: {
                id: 'xpHuUkihhxPeWYfNe38L',
                incompleteUserDetails: false,
                roles: {
                    archived: false,
                    super_user: false,
                    admin: false,
                    member: true,
                },
                linkedin_id: 'muralidhar-akkireddy-91b673158',
                last_name: 'Akkireddy',
                yoe: 1,
                github_display_name: 'Muralidhar',
                github_id: 'Muralidhar22',
                company: 'Tata Consultancy Services',
                designation: 'Assistant Systems Engineer',
                twitter_id: 'murali_14',
                first_name: 'Muralidhar',
                username: 'muralidhar',
                status: 'idle',
                picture: {
                    url: 'https://res.cloudinary.com/realdevsquad/image/upload/v1661061375/profile/xpHuUkihhxPeWYfNe38L/ogirikotjnz8esjpm51v.jpg',
                    publicId:
                        'profile/xpHuUkihhxPeWYfNe38L/ogirikotjnz8esjpm51v',
                },
            },
            taskId: 'demo-task-id-0',
        },
    ],
};
