export const mockGetOpenPrs = {
    message: 'Open PRs',
    pullRequests: [
        {
            title: 'feat: includes archived users',
            username: 'krishanu2911',
            state: 'open',
            createdAt: '2023-07-02T05:19:52Z',
            updatedAt: '2023-07-02T05:23:12Z',
            repository: 'website-backend',
            url: 'https://github.com/Real-Dev-Squad/website-backend/pull/1221',
            labels: [],
            assignees: [],
        },
        {
            title: 'Update display name',
            username: 'biswanathTewari',
            state: 'open',
            createdAt: '2023-07-02T03:45:03Z',
            updatedAt: '2023-07-02T03:45:23Z',
            repository: 'CalendarMobile',
            url: 'https://github.com/Real-Dev-Squad/CalendarMobile/pull/24',
            labels: ['RFC', 'mobile'],
            assignees: ['biswanathTewari'],
        },
        {
            title: 'add /tasks route for tasks page',
            username: 'prakashchoudhary07',
            state: 'open',
            createdAt: '2023-07-01T17:00:38Z',
            updatedAt: '2023-07-02T04:12:06Z',
            repository: 'website-status',
            url: 'https://github.com/Real-Dev-Squad/website-status/pull/674',
            labels: [],
            assignees: [],
        },
    ],
};

export const mockGetStalePrs = {
    message: 'Stale PRs',
    pullRequests: [
        {
            title: 'Setup/storybook',
            username: 'shihabus',
            state: 'open',
            createdAt: '2020-07-26T12:44:28Z',
            updatedAt: '2022-04-22T22:03:44Z',
            repository: 'website-members',
            url: 'https://github.com/Real-Dev-Squad/website-members/pull/18',
            labels: ['documentation', 'enhancement'],
            assignees: [],
        },
        {
            title: 'Initial boilerpalte for the project',
            username: 'ankurnarkhede',
            state: 'open',
            createdAt: '2020-08-09T11:52:39Z',
            updatedAt: '2020-08-28T15:31:26Z',
            repository: 'user-login',
            url: 'https://github.com/Real-Dev-Squad/user-login/pull/1',
            labels: [],
            assignees: [],
        },
        {
            title: 'Added boilerplate code for RDS Backend',
            username: 'Raunak-Agrawal',
            state: 'open',
            createdAt: '2020-08-09T16:46:48Z',
            updatedAt: '2020-08-09T16:46:48Z',
            repository: 'user-login',
            url: 'https://github.com/Real-Dev-Squad/user-login/pull/3',
            labels: [],
            assignees: [],
        },
    ],
};
